# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass

logging:
  config: /config/log-docker.xml
  level:
    root: warn
    at.wrk.fmd.mls.message: debug
