spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass

application:
  message:
    sms:
      filter:
        patterns:
        - "\\+436\\d+"
      gateway:
        url: http://localhost:8000
        username: username
        password: password

logging:
  pattern:
    console: "%d %highlight(%-5level) [%12.12thread] %cyan(%logger{5}): %msg%n"
  level:
    at.wrk.fmd.mls.message: debug
