spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass

application:
  message:
    tetra:
      gateway:
        url: http://localhost:8000

logging:
  pattern:
    console: "%d %highlight(%-5level) [%12.12thread] %cyan(%logger{5}): %msg%n"
  level:
    at.wrk.fmd.mls.message: debug
