name: Build mls-message-fleetsync Docker image

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/docker-message-fleetsync.yml
      - message-api/**
      - message-common/**
      - message-fleetsync/**
      - pom.xml
      - Dockerfile

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/docker-build.yml@main
    with:
      PROJECT_MODULE: message-fleetsync
      PROJECT_APP: message-fleetsync
      BUILD_ARGS: RUNTIME=debian-rxtx
      DOCKER_NAME: wrkfmdit/mls-message-fleetsync
    secrets:
      MLS_PACKAGES_TOKEN: ${{ secrets.MLS_PACKAGES_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
