name: Deploy mls-message Maven artifacts

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/maven-deploy-message.yml
      - message-api/**
      - message-common/**
      - pom.xml

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/maven-deploy.yml@main
    secrets:
      token: ${{ secrets.MLS_PACKAGES_TOKEN }}
